import { Ingredient } from '@/ingredients/entities/ingredient.entity';
import { Tag } from '@/tags/entities/tag.entity';
import { IngredientTag } from '@/ingredient-tags/entities/ingredient-tag.entity';
import { Logger } from '@nestjs/common';

export const ingredientTagsSeed = (
  ingredients: Ingredient[],
  tags: Tag[],
): Partial<IngredientTag>[] => {
  const ingredientTags: Partial<IngredientTag>[] = [];
  const logger = new Logger('IngredientTagsSeed');

  // Helper function to find tag by name
  const findTag = (name: string): Tag | undefined => {
    const tag = tags.find((tag) => tag.name === name);
    if (!tag) {
      logger.warn(`Tag not found: ${name}`);
    }
    return tag;
  };

  // Helper function to find ingredient by name
  const findIngredient = (name: string): Ingredient | undefined => {
    const ingredient = ingredients.find((ingredient) => ingredient.name === name);
    if (!ingredient) {
      logger.warn(`Ingredient not found: ${name}`);
    }
    return ingredient;
  };

  // Helper function to create ingredient-tag relationship
  const createIngredientTag = (ingredientName: string, tagName: string): void => {
    const ingredient = findIngredient(ingredientName);
    const tag = findTag(tagName);

    if (ingredient && tag) {
      ingredientTags.push({
        ingredient,
        tag,
      });
    } else {
      logger.warn(`Could not create relationship: ${ingredientName} - ${tagName}`);
    }
  };

  // Define ingredient-tag relationships based on CSV data
  const ingredientTagRelations = {
    'Apio (incluyendo hojas)': ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Berenjena: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Betabel: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Brócoli: [
      'Fase 2',
      'Verduras',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Calabacita: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Calabaza: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Camote: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    'Cebolla morada, blanca y amarilla': [
      'Fase 1',
      'Verduras',
      'Viernes',
      'Sábado',
      'Almuerzo',
      'Cena',
    ],
    Champiñones: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Chayote: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Arvejas: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    'Chícharos japoneses Chilacayote': [
      'Fase 1',
      'Verduras',
      'Viernes',
      'Sábado',
      'Almuerzo',
      'Cena',
    ],
    'Chile verde': ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    'Col, todos tipos': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Col rizada': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Espinaca: [
      'Fase 2',
      'Verduras',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Espirulina: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Flor de calabaza': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Frijoles: ejotes, peruano, habas': [
      'Fase 2',
      'Verduras',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Germinados: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Jícama: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Tomate: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Lechuga: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Nabos: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Nopal: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Pepino: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Pimientos: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Puerro: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    'Retoños de bambú': ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Romeritos: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Tomate verde': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Zanahoria: ['Fase 1', 'Verduras', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Acelga: ['Fase 2', 'Verduras', 'Lunes', 'Domingo', 'Desayuno', 'Almuerzo', 'Cena'],
    Apio: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    Arúgula: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    Berros: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    'Cebolla morada, blanca y amarilla Cebollitas de cambray': [
      'Fase 2',
      'Verduras',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    Chalotes: ['Fase 2', 'Verduras', 'Lunes', 'Domingo', 'Desayuno', 'Almuerzo', 'Cena'],
    Endivias: ['Fase 2', 'Verduras', 'Lunes', 'Domingo', 'Desayuno', 'Almuerzo', 'Cena'],
    Espárragos: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    'Germinado de mostaza': [
      'Fase 2',
      'Verduras',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    Hinojo: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    'Lechuga romana': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    'Pepino, todos tipos': [
      'Fase 2',
      'Verduras',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    Poro: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    'Aceitunas, todo tipo Achicoria': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Aguacate: [
      'Fase 3',
      'Grasas saludables',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Verduras',
    ],
    Alcachofas: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Alga: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Betabel: hojas, raíz Calabacitas Camote': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Cebollas: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Cebollitas de cambray': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Chilacayote: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Colecitas de Bruselas': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Coliflor: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Frijoles: ejotes, peruano, habas Germinados': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Jitomates, frescos y enlatados': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Lechuga escarola': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Palmitos, enlatados': [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Rábanos: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Zanahorias: [
      'Fase 3',
      'Verduras',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Chabacano: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Durazno: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    'Fresa ': ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Guayaba: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Higos: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Kiwi: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    'Limón: verde y amarillo': [
      'Fase 1',
      'Frutas',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Refrigerio',
    ],
    Mandarina: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Mango: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Manzanas: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Melón: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    'Melón dulce': ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    'Moras: zarzamoras, arándanos, frambuesas': [
      'Fase 1',
      'Frutas',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Refrigerio',
    ],
    Naranja: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Papaya: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Peras: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Piña: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Sandía: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    Toronja: ['Fase 1', 'Frutas', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Refrigerio'],
    'Limón: agrio y amarillo Ruibarbo': ['Fase 2', 'Frutas', 'Lunes', 'Domingo'],
    Cerezas: ['Fase 3', 'Frutas', 'Martes', 'Miércoles', 'Desayuno', 'Almuerzo'],
    Ciruelas: ['Fase 3', 'Frutas', 'Martes', 'Miércoles', 'Desayuno', 'Almuerzo'],
    Duraznos: ['Fase 3', 'Frutas', 'Martes', 'Miércoles', 'Desayuno', 'Almuerzo'],
    'Limón, agrio y amarillo': ['Fase 3', 'Frutas', 'Martes', 'Miércoles', 'Desayuno', 'Almuerzo'],
    'Moras: zarzamoras, arándanos, frambuesas Ruibarbo': [
      'Fase 3',
      'Frutas',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
    ],
    Tunas: ['Fase 3', 'Frutas', 'Martes', 'Miércoles', 'Desayuno', 'Almuerzo'],
    'Atún blanco enlatado en agua': [
      'Fase 1',
      'Proteina de origen animal',
      'Viernes',
      'Sábado',
      'Almuerzo',
      'Cena',
    ],
    'Aves de cacería: perdiz, faisán': [
      'Fase 1',
      'Proteina de origen animal',
      'Viernes',
      'Sábado',
      'Almuerzo',
      'Cena',
    ],
    'Carne de búfalo, molida': [
      'Fase 1',
      'Proteina de origen animal',
      'Viernes',
      'Sábado',
      'Almuerzo',
      'Cena',
    ],
    'Cerdo: lomo': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Embutidos libres de nitratos: pavo, pollo, res en conserva': [
      'Fase 1',
      'Proteina de origen animal',
      'Viernes',
      'Sábado',
      'Almuerzo',
      'Cena',
    ],
    'Gallina de Guinea': [
      'Fase 1',
      'Proteina de origen animal',
      'Viernes',
      'Sábado',
      'Almuerzo',
      'Cena',
    ],
    'Huevos, sólo las claras': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Pavo: pechuga, molida magra': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Pescado: blanco del Nilo, basa, oriental, blanco, barbero': [
      'Fase 1',
      'Proteina de origen animal',
      'Viernes',
      'Sábado',
      'Almuerzo',
      'Cena',
    ],
    'Pollo: sin piel, sin hueso, carne blanca': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Res: filete magro, molida': [
      'Fase 1',
      'Proteina de origen animal',
      'Viernes',
      'Sábado',
      'Almuerzo',
      'Cena',
    ],
    'Salchichas de pollo o pavo, libres de nitratos': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Sardinas enlatadas en agua': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Tocino de pavo (libre de nitratos)': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Animales de cacería: avestruz, alce, venado Atún blanco enlatado en agua': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Carne de búfalo': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    'Carne seca: res, pavo': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Cordero, cortes magros': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Embutidos libres de nitratos: pavo, pollo, rosbif': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Ostiones enlatados en agua': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Pescado: bacalao, blanco del Nilo, basa, oriental, blanco, barbero': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Res: filete magro, cortes magros, molida': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Salchichas de pollo nitratos': [
      'Fase 2',
      'Proteina de origen animal',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    Almejas: [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Atún blanco enlatado en agua Aves de cacería: faisán Calamares': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Callo de hacha': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Camarones: [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Cangrejo, carne': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Cerdo: lomo, chuletas': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Conejo: [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Cordero: [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Hígado: [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Huevos, enteros': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Langosta: [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Ostiones: [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Pavo: [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Pescado: blanco, basa, arenque, trucha': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Pollo: sin piel, sin hueso, carne blanca u oscura': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Res: filete magro, bistec': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Salmón, fresco, congelado o ahumado (libre de nitratos)': [
      'Fase 3',
      'Proteina de origen animal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Frijoles secos o enlatados': [
      'Fase 3',
      'Proteina de origen vegetal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'habas ': ['Fase 1', 'Proteina de origen vegetal', 'Viernes', 'Sábado', 'Almuerzo', 'Cena'],
    Lentejas: [
      'Fase 3',
      'Proteina de origen vegetal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Garbanzos: [
      'Fase 3',
      'Proteina de origen vegetal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Leche de almendra sin endulzar': [
      'Fase 3',
      'Proteina de origen vegetal',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Ajo fresco': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Caldos: res, pollo, verduras': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Cátsup, sin azúcar añadida, sin jarabe de maíz': [
      'Fase 2',
      'Hierbas, especias y condimentos',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Condimentos naturales: salsa tamari, sal de mar': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Endulzantes: Stevia, xilitol': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Especias: pimienta (negra, blanca), chile triturado, canela, polvo de cacao, comino Extracto de vainilla o de menta':
      [
        'Fase 1',
        'Hierbas, especias y condimentos',
        'Viernes',
        'Sábado',
        'Desayuno',
        'Almuerzo',
        'Cena',
        'Refrigerio',
      ],
    'Hierbas frescas: perejil, romero': [
      'Fase 1',
      'Hierbas, especias y condimentos',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Hierbas secas: de todo tipo': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Jengibre fresco': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Mostaza: preparada, seca': [
      'Fase 2',
      'Hierbas, especias y condimentos',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    Pepinillos: [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Vinagre: cualquier tipo': [
      'Fase 2',
      'Hierbas, especias y condimentos',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 1',
      'Viernes',
      'Sábado',
    ],
    'Ajo fresco o en polvo': [
      'Fase 2',
      'Hierbas, especias y condimentos',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Especias: pimienta (negra, blanca), chile triturado, canela, polvo de cacao, comino, sal de ajo':
      [
        'Fase 2',
        'Hierbas, especias y condimentos',
        'Lunes',
        'Domingo',
        'Desayuno',
        'Almuerzo',
        'Cena',
        'Refrigerio',
      ],
    'Extracto de vainilla o de menta': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    'Hierbas frescas: cilantro, menta, perejil, albahaca, cebollín, eneldo': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
      'Fase 2',
      'Lunes',
      'Domingo',
    ],
    'Salsa de rábano': [
      'Fase 2',
      'Hierbas, especias y condimentos',
      'Lunes',
      'Domingo',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Algarrobo: [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Especias: pimienta (negra, blanca), chile triturado, canela, polvo de cacao, polvo de curry': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Pasta de jitomate': [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Salsa: [
      'Fase 3',
      'Hierbas, especias y condimentos',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Arroz integral': [
      'Fase 1',
      'Granos y almidones',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    Cereal: ['Fase 1', 'Granos y almidones', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Cena'],
    'Galletas integrales': [
      'Fase 1',
      'Granos y almidones',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Arroz salvaje': [
      'Fase 3',
      'Granos y almidones',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
      'Almuerzo',
    ],
    Avena: [
      'Fase 3',
      'Granos y almidones',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
      'Almuerzo',
    ],
    Cebada: [
      'Fase 3',
      'Granos y almidones',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
      'Almuerzo',
    ],
    'Pan integral': [
      'Fase 1',
      'Granos y almidones',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Pasta integral': [
      'Fase 1',
      'Granos y almidones',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Harina de cacahuate': [
      'Fase 1',
      'Granos y almidones',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Leche de arroz': [
      'Fase 1',
      'Granos y almidones',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Pan de granos germinados': [
      'Fase 3',
      'Granos y almidones',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
      'Almuerzo',
    ],
    Quinoa: [
      'Fase 3',
      'Granos y almidones',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Cena',
      'Fase 1',
      'Viernes',
      'Sábado',
      'Almuerzo',
    ],
    Tapioca: ['Fase 1', 'Granos y almidones', 'Viernes', 'Sábado', 'Desayuno', 'Almuerzo', 'Cena'],
    'Trigo sarraceno': [
      'Fase 1',
      'Granos y almidones',
      'Viernes',
      'Sábado',
      'Desayuno',
      'Almuerzo',
      'Cena',
    ],
    'Arroz integral negro': [
      'Fase 3',
      'Granos y almidones',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Cena',
    ],
    'Aceites: semilla de uva, oliva, ajonjolí': [
      'Fase 3',
      'Grasas saludables',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Humus: [
      'Fase 3',
      'Grasas saludables',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Mantequillas y cremas crudas de nueces o semillas': [
      'Fase 3',
      'Grasas saludables',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Mayonesa de cártamo': [
      'Fase 3',
      'Grasas saludables',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Nueces, crudas: almendras, castañas, pecanas, pistaches, avellanas, piñones, nueces': [
      'Fase 3',
      'Grasas saludables',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    'Semillas, crudas: lino, cáñamo, calabaza, ajonjolí, girasol': [
      'Fase 3',
      'Grasas saludables',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
    Tahina: [
      'Fase 3',
      'Grasas saludables',
      'Martes',
      'Miércoles',
      'Desayuno',
      'Almuerzo',
      'Cena',
      'Refrigerio',
    ],
  };

  // Create relationships from the mapping
  Object.entries(ingredientTagRelations).forEach(([ingredientName, tagNames]) => {
    tagNames.forEach((tagName) => {
      createIngredientTag(ingredientName, tagName);
    });
  });

  logger.log(`Successfully created ${ingredientTags.length} ingredient-tag relationships`);
  return ingredientTags;
};
